# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

class AnyHint(object):
    NONE = 0
    DmaDescriptorHint = 1
    InstructionHint = 2
    InterruptHint = 3
    FenceHint = 4

