# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

class DataType(object):
    FIXED_POINT8 = 0
    FIXED_POINT16 = 1
    SIGNED_FIXED_POINT32 = 2
    BFLOAT = 3
    HALF = 4
    SINGLE = 5
    SIGNED_FIXED_POINT8 = 8
    SIGNED_FIXED_POINT16 = 9

