# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

class Description(object):
    BASE_ADDRESS_OUTPUT_ACTIVATION = 0
    BASE_ADDRESS_INPUT_ACTIVATION = 1
    BASE_ADDRESS_PARAMETER = 2
    BASE_ADDRESS_SCRATCH = 3

