# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DmaDescriptorHint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDmaDescriptorHint(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DmaDescriptorHint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def DmaDescriptorHintBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # DmaDescriptorHint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DmaDescriptorHint
    def Meta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Meta import Meta
            obj = Meta()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DmaDescriptorHint
    def OffsetInBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DmaDescriptorHint
    def SizeInBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DmaDescriptorHintStart(builder): builder.StartObject(3)
def DmaDescriptorHintAddMeta(builder, meta): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(meta), 0)
def DmaDescriptorHintAddOffsetInBytes(builder, offsetInBytes): builder.PrependInt32Slot(1, offsetInBytes, 0)
def DmaDescriptorHintAddSizeInBytes(builder, sizeInBytes): builder.PrependInt32Slot(2, sizeInBytes, 0)
def DmaDescriptorHintEnd(builder): return builder.EndObject()
