# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FenceHint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFenceHint(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FenceHint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def FenceHintBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # FenceHint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FenceHintStart(builder): builder.StartObject(0)
def FenceHintEnd(builder): return builder.EndObject()
