# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldOffset(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFieldOffset(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldOffset()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def FieldOffsetBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # FieldOffset
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldOffset
    def Meta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Meta import Meta
            obj = Meta()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FieldOffset
    def OffsetBit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FieldOffsetStart(builder): builder.StartObject(2)
def FieldOffsetAddMeta(builder, meta): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(meta), 0)
def FieldOffsetAddOffsetBit(builder, offsetBit): builder.PrependInt32Slot(1, offsetBit, 0)
def FieldOffsetEnd(builder): return builder.EndObject()
