# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InputLayer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInputLayer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InputLayer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def InputLayerBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # InputLayer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def InputLayerStart(builder): builder.StartObject(0)
def InputLayerEnd(builder): return builder.EndObject()
