# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InstructionHint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInstructionHint(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InstructionHint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def InstructionHintBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # InstructionHint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InstructionHint
    def InstructionChunkIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def InstructionHintStart(builder): builder.StartObject(1)
def InstructionHintAddInstructionChunkIndex(builder, instructionChunkIndex): builder.PrependInt32Slot(0, instructionChunkIndex, 0)
def InstructionHintEnd(builder): return builder.EndObject()
