# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InstructionBitstream(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInstructionBitstream(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InstructionBitstream()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def InstructionBitstreamBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # InstructionBitstream
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InstructionBitstream
    def Bitstream(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # InstructionBitstream
    def BitstreamAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # InstructionBitstream
    def BitstreamLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InstructionBitstream
    def BitstreamIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # InstructionBitstream
    def FieldOffsets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FieldOffset import FieldOffset
            obj = FieldOffset()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InstructionBitstream
    def FieldOffsetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InstructionBitstream
    def FieldOffsetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def InstructionBitstreamStart(builder): builder.StartObject(2)
def InstructionBitstreamAddBitstream(builder, bitstream): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bitstream), 0)
def InstructionBitstreamStartBitstreamVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def InstructionBitstreamAddFieldOffsets(builder, fieldOffsets): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fieldOffsets), 0)
def InstructionBitstreamStartFieldOffsetsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def InstructionBitstreamEnd(builder): return builder.EndObject()
