# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

class InterruptType(object):
    SCALAR_CORE_INT_0 = 0
    SCALAR_CORE_INT_1 = 1
    SCALAR_CORE_INT_2 = 2
    SCALAR_CORE_INT_3 = 3

