# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InterruptHint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInterruptHint(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InterruptHint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def InterruptHintBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # InterruptHint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InterruptHint
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def InterruptHintStart(builder): builder.StartObject(1)
def InterruptHintAddType(builder, type): builder.PrependInt16Slot(0, type, 0)
def InterruptHintEnd(builder): return builder.EndObject()
