# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NumericsConstants(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNumericsConstants(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NumericsConstants()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def NumericsConstantsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # NumericsConstants
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NumericsConstants
    def ZeroPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NumericsConstants
    def DequantizationFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def NumericsConstantsStart(builder): builder.StartObject(2)
def NumericsConstantsAddZeroPoint(builder, zeroPoint): builder.PrependInt32Slot(0, zeroPoint, 0)
def NumericsConstantsAddDequantizationFactor(builder, dequantizationFactor): builder.PrependFloat32Slot(1, dequantizationFactor, 0.0)
def NumericsConstantsEnd(builder): return builder.EndObject()
