# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OutputLayout(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOutputLayout(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OutputLayout()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def OutputLayoutBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # OutputLayout
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OutputLayout
    def YCoordinateToLinearTileIdMap(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def YCoordinateToLinearTileIdMapAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def YCoordinateToLinearTileIdMapLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def YCoordinateToLinearTileIdMapIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # OutputLayout
    def XCoordinateToLinearTileIdMap(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def XCoordinateToLinearTileIdMapAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def XCoordinateToLinearTileIdMapLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def XCoordinateToLinearTileIdMapIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # OutputLayout
    def LinearizedTileByteOffset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def LinearizedTileByteOffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def LinearizedTileByteOffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def LinearizedTileByteOffsetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # OutputLayout
    def XCoordinateToLocalByteOffset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def XCoordinateToLocalByteOffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def XCoordinateToLocalByteOffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def XCoordinateToLocalByteOffsetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # OutputLayout
    def YCoordinateToLocalYOffset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def YCoordinateToLocalYOffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def YCoordinateToLocalYOffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def YCoordinateToLocalYOffsetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # OutputLayout
    def XCoordinateToLocalYRowSize(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # OutputLayout
    def XCoordinateToLocalYRowSizeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # OutputLayout
    def XCoordinateToLocalYRowSizeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OutputLayout
    def XCoordinateToLocalYRowSizeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def OutputLayoutStart(builder): builder.StartObject(6)
def OutputLayoutAddYCoordinateToLinearTileIdMap(builder, yCoordinateToLinearTileIdMap): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(yCoordinateToLinearTileIdMap), 0)
def OutputLayoutStartYCoordinateToLinearTileIdMapVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutAddXCoordinateToLinearTileIdMap(builder, xCoordinateToLinearTileIdMap): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(xCoordinateToLinearTileIdMap), 0)
def OutputLayoutStartXCoordinateToLinearTileIdMapVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutAddLinearizedTileByteOffset(builder, linearizedTileByteOffset): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(linearizedTileByteOffset), 0)
def OutputLayoutStartLinearizedTileByteOffsetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutAddXCoordinateToLocalByteOffset(builder, xCoordinateToLocalByteOffset): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(xCoordinateToLocalByteOffset), 0)
def OutputLayoutStartXCoordinateToLocalByteOffsetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutAddYCoordinateToLocalYOffset(builder, yCoordinateToLocalYOffset): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(yCoordinateToLocalYOffset), 0)
def OutputLayoutStartYCoordinateToLocalYOffsetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutAddXCoordinateToLocalYRowSize(builder, xCoordinateToLocalYRowSize): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(xCoordinateToLocalYRowSize), 0)
def OutputLayoutStartXCoordinateToLocalYRowSizeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OutputLayoutEnd(builder): return builder.EndObject()
