# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OutputLayer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOutputLayer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OutputLayer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def OutputLayerBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # OutputLayer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OutputLayer
    def Layout(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .OutputLayout import OutputLayout
            obj = OutputLayout()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OutputLayer
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # OutputLayer
    def ShapeInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .OutputShapeInfo import OutputShapeInfo
            obj = OutputShapeInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OutputLayerStart(builder): builder.StartObject(3)
def OutputLayerAddLayout(builder, layout): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(layout), 0)
def OutputLayerAddDataType(builder, dataType): builder.PrependInt16Slot(1, dataType, 0)
def OutputLayerAddShapeInfo(builder, shapeInfo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(shapeInfo), 0)
def OutputLayerEnd(builder): return builder.EndObject()
