# automatically generated by the FlatBuffers compiler, do not modify

# namespace: darwinn

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TensorShape(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTensorShape(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TensorShape()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def TensorShapeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x57\x4E\x31", size_prefixed=size_prefixed)

    # TensorShape
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TensorShape
    def Dimension(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from .Range import Range
            obj = Range()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TensorShape
    def DimensionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TensorShape
    def DimensionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TensorShapeStart(builder): builder.StartObject(1)
def TensorShapeAddDimension(builder, dimension): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dimension), 0)
def TensorShapeStartDimensionVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def TensorShapeEnd(builder): return builder.EndObject()
